AWSTemplateFormatVersion: 2010-09-09

Description: Resources for KeePass database storage using the KeeAnywhere plugin.

Resources:

  StorageBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  StorageBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref StorageBucket
      PolicyDocument:
        Statement:
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub "arn:aws:s3:::${StorageBucket}"
              - !Sub "arn:aws:s3:::${StorageBucket}/*"
            Condition:
              Bool:
                'aws:SecureTransport': false

  KeePassUser1:
    Type: 'AWS::IAM::User'
    Properties:
      Policies:
        - PolicyName: KeePass-Storage-Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:ListBucketVersions'
                  - 's3:ListBucket'
                Resource:
                  - !Sub "arn:aws:s3:::${StorageBucket}"
              - Effect: Allow
                Action:
                  - 's3:DeleteObject'
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:GetObjectVersionTagging'
                  - 's3:PutObject'
                Resource:
                  - !Sub "arn:aws:s3:::${StorageBucket}/*"
              - Effect: Allow
                Action:
                  - 's3:ListAllMyBuckets'
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub "keepass-storage-1-user"
        

Outputs:
  StorageBucket:
    Value: !Ref StorageBucket

  KeePassUser1:
    Value: !Ref KeePassUser1
